services:
  synapnote-frontend:
    image: synapnote-frontend:latest
    container_name: synapnote-frontend
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - synapnote-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped

